import { describe, it, expect, afterEach } from "vitest";
import { rm, readFile, mkdtemp } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import * as path from "node:path";
import { makeTree, concept } from "./helpers.js";
import {
  composeLocalAgents,
  composeInteractiveBody,
  selectLocalAgents,
  localAgentSlug,
  opencodeModelFor,
} from "../src/local/agents-core.js";
import { exportLocalAgents } from "../src/local/agents.js";
import { agentFromConcept, type AgentConcept } from "../src/agents/concept.js";
import { parseConcept } from "../src/okf/frontmatter.js";
import type { InstanceConfig } from "../src/instance/config-core.js";
import { DEFAULT_CONFIG } from "../src/instance/config-core.js";
import { scaffoldBrain } from "../src/init/scaffold.js";
import { main } from "../src/cli.js";

/**
 * Local agent surfaces — the persona compiles from the SAME concept file the
 * scheduled tiers run on, into Claude Code + opencode artifacts. These prove
 * the compile contract: shared body, surface-specific frontmatter, persona
 * slug on the hub, D11 still enforced, artifacts regenerable.
 */

const roots: string[] = [];
afterEach(async () => {
  while (roots.length) await rm(roots.pop()!, { recursive: true, force: true });
});

function agentConcept(
  name: string,
  extra: Record<string, unknown> = {},
  body = "Coordinate the mesh and brief the principal.",
): AgentConcept {
  const raw = concept("agent", { name, title: `${name} title`, level: "L3", model: "kimi-for-coding", harness: "moonshot-api", ...extra }, body);
  const parsed = parseConcept(raw)!;
  return agentFromConcept({
    path: `agents/${name}.md`,
    relPath: `agents/${name}.md`,
    frontmatter: parsed.frontmatter,
    body: parsed.body,
    missingFrontmatter: false,
  });
}

const config: InstanceConfig = {
  ...DEFAULT_CONFIG,
  engine: { repo: "github.com/example/engine", ref: "v0.11.0" },
  identity: {
    principal: { name: "Ada Lovelace" },
    persona: { name: "Quill Byron" },
  },
  delivery: { channels: ["discord"], deliverAgent: "chief-of-staff" },
};

describe("localAgentSlug / opencodeModelFor", () => {
  it("hub exports under the persona's first name; spokes under their own", () => {
    expect(localAgentSlug(agentConcept("chief-of-staff"), config)).toBe("quill");
    expect(localAgentSlug(agentConcept("bookkeeper"), config)).toBe("bookkeeper");
  });

  it("no persona → hub keeps its agent name", () => {
    const bare = { ...config, identity: { principal: { name: "Ada" } } };
    expect(localAgentSlug(agentConcept("chief-of-staff"), bare)).toBe("chief-of-staff");
  });

  it("maps bare model names to provider/model; passes slashed names through; config overrides all", () => {
    expect(opencodeModelFor(agentConcept("a"), config)).toBe("kimi-code/kimi-for-coding");
    expect(opencodeModelFor(agentConcept("a", { model: "k3" }), config)).toBe("kimi-code/k3");
    expect(opencodeModelFor(agentConcept("a", { model: "kimi-code/kimi-for-coding" }), config)).toBe("kimi-code/kimi-for-coding");
    expect(opencodeModelFor(agentConcept("a", { model: "sonnet" }), config)).toBe("anthropic/claude-sonnet-5");
    const overridden = { ...config, localAgents: { opencodeModel: "kimi-code/k3" } };
    expect(opencodeModelFor(agentConcept("a"), overridden)).toBe("kimi-code/k3");
  });
});

describe("composeLocalAgents — the compile contract", () => {
  it("emits both artifacts with identical bodies and surface-specific frontmatter", () => {
    const artifacts = composeLocalAgents(agentConcept("chief-of-staff"), config);
    expect(artifacts.map((a) => a.relPath)).toEqual([
      ".claude/agents/quill.md",
      ".opencode/agents/quill.md",
    ]);
    const [claude, opencode] = artifacts.map((a) => a.content);
    expect(claude).toContain("name: quill");
    expect(claude).toContain("description:");
    expect(opencode).toContain("mode: primary");
    expect(opencode).toContain("model: kimi-code/kimi-for-coding");
    // Same composed body after frontmatter.
    const body = composeInteractiveBody(agentConcept("chief-of-staff"), config);
    expect(claude).toContain(body);
    expect(opencode).toContain(body);
  });

  it("body carries the job verbatim, the session rules, and the generated marker", () => {
    const body = composeInteractiveBody(agentConcept("chief-of-staff", {}, "Be the hub. Lead with nags."), config);
    expect(body).toContain("Be the hub. Lead with nags.");
    expect(body).toContain("GENERATED by `anima-mesh export-local`");
    expect(body).toContain("bundle/agents/chief-of-staff.md");
    expect(body).toContain("READ-ONLY");
    expect(body).toContain("Ada Lovelace");
    expect(body).toContain("Never echo secret values");
  });

  it("defect instructions appear only when the whitelist carries defect-report", () => {
    const without = composeInteractiveBody(agentConcept("chief-of-staff"), config);
    expect(without).not.toContain("Engine defects");
    const withIt = composeInteractiveBody(
      agentConcept("chief-of-staff", { whitelist: ["defect-report"] }),
      config,
    );
    expect(withIt).toContain("Engine defects");
    expect(withIt).toContain("drafts/defects/<slug>.md");
    expect(withIt).toContain("anima-mesh defect file");
    expect(withIt).toContain("gh issue create --repo example/engine");
    expect(withIt).toContain("De-identify even");
  });

  it("spokes are opencode subagents", () => {
    const [, opencode] = composeLocalAgents(agentConcept("bookkeeper"), config);
    expect(opencode!.content).toContain("mode: subagent");
  });

  it("a persona already baked into the title is not repeated in the description", () => {
    const hub = agentConcept("chief-of-staff", { title: "Quill Byron — Chief of Staff" });
    const [claude] = composeLocalAgents(hub, config);
    expect(claude!.content).toContain("Quill Byron — Chief of Staff. Interactive");
    expect(claude!.content).not.toContain("Quill Byron — Quill Byron");
  });
});

describe("selectLocalAgents — roster + D11", () => {
  const roster = [
    agentConcept("chief-of-staff"),
    agentConcept("bookkeeper"),
    agentConcept("sales-qualification", { commercial: true }),
  ];

  it("default is the hub only; localAgents.agents overrides", () => {
    expect(selectLocalAgents(roster, config).agents.map((a) => a.name)).toEqual(["chief-of-staff"]);
    const custom = { ...config, localAgents: { agents: ["bookkeeper"] } };
    expect(selectLocalAgents(roster, custom).agents.map((a) => a.name)).toEqual(["bookkeeper"]);
  });

  it("--all exports the activatable and reports the dual-gated skip", () => {
    const sel = selectLocalAgents(roster, config, { all: true });
    expect(sel.agents.map((a) => a.name)).toEqual(["chief-of-staff", "bookkeeper"]);
    expect(sel.skipped).toHaveLength(1);
    expect(sel.skipped[0]!.name).toBe("sales-qualification");
    expect(sel.skipped[0]!.reason).toContain("dual-gated");
  });

  it("naming a dual-gated commercial agent explicitly fails loudly", () => {
    expect(() => selectLocalAgents(roster, config, { names: ["sales-qualification"] })).toThrow(/dual-gated/);
    expect(() => selectLocalAgents(roster, config, { names: ["nope"] })).toThrow(/not found/);
  });
});

describe("exportLocalAgents + CLI — disk half", () => {
  async function makeInstance(): Promise<string> {
    const root = await makeTree({
      "animamesh.config.json": JSON.stringify({
        bundle: "bundle",
        engine: { repo: "github.com/example/engine" },
        identity: { principal: { name: "Ada" }, persona: { name: "Quill" } },
        delivery: { deliverAgent: "hub" },
      }),
      "bundle/index.md": concept("index", {}, "# Index\n"),
      "bundle/log.md": concept("log", {}, "# Log\n"),
      "bundle/constitution.md": concept("constitution", { immutable: true }, "# Constitution\n"),
      "bundle/agents/hub.md": concept(
        "agent",
        { name: "hub", title: "Hub", level: "L3", model: "kimi-for-coding", harness: "moonshot-api" },
        "Coordinate.",
      ),
    });
    roots.push(root);
    return root;
  }

  it("writes both artifacts under the instance root", async () => {
    const root = await makeInstance();
    const result = await exportLocalAgents(root);
    expect(result.written).toEqual([".claude/agents/quill.md", ".opencode/agents/quill.md"]);
    const written = await readFile(path.join(root, ".claude/agents/quill.md"), "utf8");
    expect(written).toContain("Coordinate.");
  });

  it("the CLI command exports and reports", async () => {
    const root = await makeInstance();
    const lines: string[] = [];
    const code = await main(["export-local", "--instance", root], {
      log: (s) => lines.push(s),
      error: (s) => lines.push(s),
    });
    expect(code).toBe(0);
    expect(lines.join("\n")).toContain("wrote .claude/agents/quill.md");
    expect(existsSync(path.join(root, ".opencode/agents/quill.md"))).toBe(true);
  });
});

describe("scaffold — new instances get local surfaces out of the box", () => {
  it("init writes hub artifacts when the roster has a hub", async () => {
    const dir = await mkdtemp(path.join(tmpdir(), "animamesh-init-"));
    roots.push(dir);
    const result = await scaffoldBrain(dir, {
      orgName: "Acme Co",
      principalName: "Ada",
      personaName: "Quill",
      agents: ["chief-of-staff", "compliance-ops"],
      now: "2026-07-23T00:00:00.000Z",
    });
    expect(result.conformance.ok).toBe(true);
    expect(result.created).toContain(".claude/agents/quill.md");
    expect(result.created).toContain(".opencode/agents/quill.md");
    const body = await readFile(path.join(dir, ".opencode/agents/quill.md"), "utf8");
    expect(body).toContain("mode: primary");
  });

  it("a hub-less roster scaffolds cleanly with no artifacts", async () => {
    const dir = await mkdtemp(path.join(tmpdir(), "animamesh-init-"));
    roots.push(dir);
    const result = await scaffoldBrain(dir, {
      orgName: "Acme Co",
      principalName: "Ada",
      agents: ["compliance-ops"],
      now: "2026-07-23T00:00:00.000Z",
    });
    expect(result.conformance.ok).toBe(true);
    expect(result.created.some((f) => f.startsWith(".claude/agents/"))).toBe(false);
  });
});
