import type { AgentConcept } from "../agents/concept.js";
import { assertActivatable } from "../agents/concept.js";
import type { InstanceConfig } from "../instance/config-core.js";
import { levelMeaning } from "../harness/run-core.js";
import { engineRepoSlug } from "../defects/report-core.js";

/**
 * Local agent surfaces — the third tier.
 *
 * The persona IS the concept file: `bundle/agents/<name>.md` is the single
 * source of truth for who an agent is on every tier. Scheduled runs wrap it
 * with `buildPrompt` (context inlined, L1 needs no tools); direction runs
 * wrap it with `buildDirectionPrompt`; and this module compiles it into
 * INTERACTIVE agent artifacts for local coding terminals:
 *
 *   .claude/agents/<slug>.md    — Claude Code (`@agent-<slug>`, or a whole
 *                                 session via `claude --agent <slug>`)
 *   .opencode/agents/<slug>.md  — opencode (Tab-switch primary agent, or
 *                                 `opencode run --agent <slug>`)
 *
 * Artifacts are GENERATED, never hand-edited: tune the personality in the
 * concept file and re-run `anima-mesh export-local`. Interactive sessions
 * have tools, so context is not inlined — the prompt instructs the agent to
 * READ the live bundle, which keeps artifacts evergreen between exports.
 */

export interface LocalAgentArtifact {
  /** Path relative to the instance root. */
  relPath: string;
  content: string;
}

/**
 * The hub (the persona-carrying, single-communication-surface agent) exports
 * under the persona's first name — that is the name the principal talks to.
 * Spokes export under their agent names. Same default as direction routing.
 */
export function localHubName(config: InstanceConfig): string {
  return config.delivery?.deliverAgent ?? "chief-of-staff";
}

export function localAgentSlug(agent: AgentConcept, config: InstanceConfig): string {
  const persona = config.identity?.persona?.name?.trim();
  if (agent.name === localHubName(config) && persona) {
    const first = sanitizeSlug(persona.split(/\s+/)[0] ?? "");
    if (first) return first;
  }
  return sanitizeSlug(agent.name) || agent.name;
}

function sanitizeSlug(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * opencode wants `provider/model`. Frontmatter values already shaped that
 * way pass through; bare names get the engine's best-known provider prefix.
 * `localAgents.opencodeModel` in the instance config overrides everything —
 * the "which brain, locally" knob.
 */
export function opencodeModelFor(agent: AgentConcept, config: InstanceConfig): string {
  const override = config.localAgents?.opencodeModel;
  if (override) return override;
  const m = agent.model;
  if (m.includes("/")) return m;
  // Kimi-for-Coding subscription endpoint models (see providers/opencode.ts).
  if (m === "kimi-for-coding" || m === "kimi-for-coding-highspeed" || m === "k3") return `kimi-code/${m}`;
  if (m.startsWith("kimi-")) return `moonshot/${m}`;
  if (m === "sonnet") return "anthropic/claude-sonnet-5";
  if (m === "opus") return "anthropic/claude-opus-4-8";
  if (m === "haiku") return "anthropic/claude-haiku-4-5";
  if (m.startsWith("claude-")) return `anthropic/${m}`;
  return m;
}

/** YAML-safe single-line scalar (JSON strings are valid YAML). */
function yamlString(s: string): string {
  return JSON.stringify(s);
}

export function localAgentDescription(agent: AgentConcept, config: InstanceConfig): string {
  const persona = config.identity?.persona?.name?.trim();
  const isHub = agent.name === localHubName(config);
  // Many instances bake the persona into the title already — don't repeat it.
  const who = isHub && persona && !agent.title.includes(persona) ? `${persona} — ${agent.title}` : agent.title;
  const callName = isHub && persona ? persona : agent.title;
  return (
    `${who}. Interactive working session over this AnimaMesh instance: stand-up, proposals, ` +
    `and drafting grounded in the live bundle. Use when the user wants to talk to ${callName} ` +
    `or work the mesh interactively.`
  );
}

/**
 * The shared interactive system prompt — identical body in both artifacts,
 * composed from the same `AgentConcept` the scheduled tiers run on.
 */
export function composeInteractiveBody(agent: AgentConcept, config: InstanceConfig): string {
  const principal = config.identity?.principal?.name ?? "the principal";
  const b = config.bundle;
  const sourcePath = `${b}/${agent.relPath}`;
  const sections: string[] = [];

  sections.push(
    `<!-- GENERATED by \`anima-mesh export-local\`. Source of truth: ${sourcePath} +`,
    `     animamesh.config.json. Edit those and re-run the export — do not edit this file. -->`,
    "",
    `You are "${agent.title}" (${agent.name}), an agent in an AnimaMesh company-of-0 mesh —`,
    `here in a LIVE interactive working session with ${principal}, your principal.`,
    `Autonomy level: ${agent.level} (${levelMeaning(agent.level)}). The autonomy ladder and the`,
    `constitution bind in this session exactly as they do on scheduled runs.`,
    "",
    "## Your job",
    "",
    agent.job,
    "",
    "## Interactive session rules",
    "",
    "- This is a conversation, not a heartbeat run: the principal is present. Ask, propose, and",
    "  iterate; keep replies tight and lead with what matters.",
    "- You are launched inside the instance repo. Ground EVERY stable-fact claim by reading the",
    `  bundle — never recall. At session start, read: \`${b}/index.md\`, \`${b}/ops/nags.md\`,`,
    `  \`${b}/ops/calendar.md\`, \`${b}/ops/watch-list.md\`, the latest 2–3 files in`,
    `  \`${config.reports}/\`, and pending items in \`${config.approvals}/\`.`,
    "- Open with a compact stand-up: active nags first, then what moved since the last brief,",
    "  then the single question most worth the principal's time right now.",
    `- The bundle is READ-ONLY in interactive sessions: never create or edit files under \`${b}/\``,
    "  (`constitution.md` is never yours to touch on any tier). Session work products go under",
    `  \`${config.drafts}/\` — state the path whenever you write one.`,
    "- Consequential actions (money movement, government filings, external publishing,",
    "  credentials, access expansion, anything public under your name) end at the principal,",
    "  always — propose, never perform.",
    "- Never echo secret values (.env files, tokens, keys); refer to variables by name only.",
  );

  const engineRepo = engineRepoSlug(config);
  if (agent.whitelist.includes("defect-report") && engineRepo) {
    sections.push(
      "",
      "## Engine defects",
      "",
      "When the AnimaMesh ENGINE misbehaves (harness, CLI, or Workers bugs — not this instance's",
      `content), log it as a GitHub issue on \`${engineRepo}\`:`,
      "",
      "- The engine repo is PUBLIC — de-identify first: no names or emails of the organization,",
      "  principal, or persona; no bundle content; describe the mechanics generically.",
      `- Use: \`gh issue create --repo ${engineRepo} --label defect --title "<one-line summary>"`,
      `  --body "<repro steps, expected vs actual, engine ref>"\``,
      `- If \`gh\` is unavailable or unauthenticated, write the same content to`,
      `  \`${config.drafts}/defects/<yyyy-mm-dd>-<slug>.md\` and tell the principal.`,
    );
  }

  sections.push(
    "",
    `*Persona source of truth: \`${sourcePath}\` — tune the personality there and regenerate*`,
    "*with `anima-mesh export-local`.*",
  );

  return sections.join("\n");
}

/** Both artifacts for one agent: same body, surface-specific frontmatter. */
export function composeLocalAgents(agent: AgentConcept, config: InstanceConfig): LocalAgentArtifact[] {
  const slug = localAgentSlug(agent, config);
  const body = composeInteractiveBody(agent, config);
  const description = localAgentDescription(agent, config);
  const isHub = agent.name === localHubName(config);
  const claudeModel = config.localAgents?.claudeModel;

  const claude = [
    "---",
    `name: ${slug}`,
    `description: ${yamlString(description)}`,
    ...(claudeModel ? [`model: ${claudeModel}`] : []),
    "---",
    "",
    body,
    "",
  ].join("\n");

  const opencode = [
    "---",
    `description: ${yamlString(description)}`,
    `mode: ${isHub ? "primary" : "subagent"}`,
    `model: ${opencodeModelFor(agent, config)}`,
    "---",
    "",
    body,
    "",
  ].join("\n");

  return [
    { relPath: `.claude/agents/${slug}.md`, content: claude },
    { relPath: `.opencode/agents/${slug}.md`, content: opencode },
  ];
}

export interface LocalAgentSelection {
  agents: AgentConcept[];
  skipped: { name: string; reason: string }[];
}

/**
 * Which agents get local surfaces. Explicit names fail loudly (including the
 * D11 dual gate — a local chat surface is still capability); `--all` exports
 * everything activatable and reports what it skipped; the default is the
 * hub, or the instance's `localAgents.agents` list when configured.
 */
export function selectLocalAgents(
  all: AgentConcept[],
  config: InstanceConfig,
  opts: { names?: string[]; all?: boolean } = {},
): LocalAgentSelection {
  const byName = new Map(all.map((a) => [a.name, a]));
  if (opts.names && opts.names.length > 0) {
    const agents = opts.names.map((n) => {
      const found = byName.get(n);
      if (!found) {
        throw new Error(`agent '${n}' not found — available: ${all.map((a) => a.name).join(", ") || "(none)"}`);
      }
      assertActivatable(found, config);
      return found;
    });
    return { agents, skipped: [] };
  }
  if (opts.all) {
    const agents: AgentConcept[] = [];
    const skipped: { name: string; reason: string }[] = [];
    for (const a of all) {
      try {
        assertActivatable(a, config);
        agents.push(a);
      } catch (err) {
        skipped.push({ name: a.name, reason: err instanceof Error ? err.message : String(err) });
      }
    }
    return { agents, skipped };
  }
  const defaults = config.localAgents?.agents ?? [localHubName(config)];
  return selectLocalAgents(all, config, { names: defaults });
}
